### ISSUE TITLE
await in a python lambda

### ISSUE THREAD

**Issue by cleder** [mristin/fastapi-icontract#3]
I just stumbled upon this:
https://stackoverflow.com/a/66330279/674447

Maybe that could be helpful?

**Comment by mristin** [comment]
Thanks, I'll add it to the documentation!

**Comment by mristin** [comment]
Hi @cleder,
I finally decided against referencing the answer in the docs. I also added an additional answer to that StackOverflow question -- is there a glaring bit I am missing there?

I also updated the documentation on async conditions in icontract: https://icontract.readthedocs.io/en/latest/async.html#special-considerations

There are also two new functions I added to asyncstdlib 3.9.1 (https://github.com/maxfischer2781/asyncstdlib/releases/tag/v3.9.1) which hopefully alleviate the issues with lack of async lambdas.

Please let me know if you'd like me to expand on it more, or point me to what I am missing as I don't use async that much.

**Comment by mristin** [comment]
Hi @cleder ,
I included afterwards an example with `asyncstdlib.apply` and added a full example to the StackOverflow answer: https://stackoverflow.com/a/66536848/1600678
